/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Entreprise.Entreprise;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author clementraphaell
 */
public class interfaceGraphiqueAccueil extends javax.swing.JFrame {
    /**
     * Creates new form interfaceGraphiqueAccueil
     */
    Entreprise entreprise;
    
    public interfaceGraphiqueAccueil() throws NumberFormatException, IOException {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.entreprise = new Entreprise();
        this.entreprise.initDonnees();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAccueil = new javax.swing.JLabel();
        buttonGestionPers = new javax.swing.JButton();
        buttonGestionMiss = new javax.swing.JButton();
        buttonGestionComp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(225, 225, 213));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        labelAccueil.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        labelAccueil.setText("Accueil");
        labelAccueil.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelAccueil.setAlignmentX(1.0F);
        labelAccueil.setAlignmentY(1.0F);
        labelAccueil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAccueil.setMaximumSize(new java.awt.Dimension(70, 18));
        labelAccueil.setPreferredSize(new java.awt.Dimension(60, 60));

        buttonGestionPers.setForeground(new java.awt.Color(119, 119, 119));
        buttonGestionPers.setText("Gestion du personnel");
        buttonGestionPers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGestionPersMouseClicked(evt);
            }
        });
        buttonGestionPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionPersActionPerformed(evt);
            }
        });

        buttonGestionMiss.setForeground(new java.awt.Color(119, 119, 119));
        buttonGestionMiss.setText("Gestion des missions");
        buttonGestionMiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGestionMissMouseClicked(evt);
            }
        });

        buttonGestionComp.setForeground(new java.awt.Color(119, 119, 119));
        buttonGestionComp.setText("Gestion des compétences");
        buttonGestionComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGestionCompMouseClicked(evt);
            }
        });
        buttonGestionComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionCompActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Statistique");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\jerem\\Desktop\\projetJava2\\images\\Capture2.JPG")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\jerem\\Desktop\\projetJava2\\images\\Capture.JPG")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(labelAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonGestionMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGestionPers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGestionComp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(641, 641, 641)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonGestionMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonGestionPers, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonGestionComp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGestionPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionPersActionPerformed
        // TODO add your handling code here 
    }//GEN-LAST:event_buttonGestionPersActionPerformed

    private void buttonGestionCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionCompActionPerformed

    private void buttonGestionPersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGestionPersMouseClicked
        // TODO add your handling code here:
        InterfaceGraphiquePersonnel Personnel = null;
        try {
            Personnel = new InterfaceGraphiquePersonnel();
        } catch (IOException ex) {
            Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        Personnel.setVisible(true);
    }//GEN-LAST:event_buttonGestionPersMouseClicked

    private void buttonGestionMissMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGestionMissMouseClicked
        // TODO add your handling code here:
        InterfaceGraphiqueMissions Missions = new InterfaceGraphiqueMissions();
        this.dispose();
        Missions.setVisible(true);
    }//GEN-LAST:event_buttonGestionMissMouseClicked

    private void buttonGestionCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGestionCompMouseClicked
        // TODO add your handling code here:
        InterfaceGraphiqueCompetences Competences = null;
        try {
            Competences = new InterfaceGraphiqueCompetences();
        } catch (IOException ex) {
            Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        Competences.setVisible(true);
    }//GEN-LAST:event_buttonGestionCompMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new interfaceGraphiqueAccueil().setVisible(true);
                } catch (NumberFormatException ex) {
                    Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(interfaceGraphiqueAccueil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGestionComp;
    private javax.swing.JButton buttonGestionMiss;
    private javax.swing.JButton buttonGestionPers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAccueil;
    // End of variables declaration//GEN-END:variables

    
}
