/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Competence.Competence;
import Entreprise.Entreprise;
import Personnel.Personnel;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author clementraphaell
 */
public class interfaceGraphiqueAjouteComp extends javax.swing.JFrame {
    Entreprise entreprise;
    
    
    public interfaceGraphiqueAjouteComp() throws IOException {
        initComponents();
        this.entreprise = new Entreprise();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAjoutComp = new javax.swing.JPanel();
        buttonAjoutComp = new javax.swing.JButton();
        buttonRetourComp = new javax.swing.JButton();
        labelAjoutComp = new javax.swing.JLabel();
        LabelAjouterCompVerif = new javax.swing.JLabel();
        LabelLibFrAjoutComp = new javax.swing.JLabel();
        TextLibelleFrAjoutAccueil = new javax.swing.JTextField();
        labelLibEnAjoutComp = new javax.swing.JLabel();
        TextLibelleEnAjoutAccueil = new javax.swing.JTextField();
        TextIdAjoutComp = new javax.swing.JTextField();
        LabelIdAjoutComp = new javax.swing.JLabel();
        LabelMsgErreurAjoutComp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAjoutComp.setBackground(new java.awt.Color(225, 225, 213));

        buttonAjoutComp.setText("Ajouter");
        buttonAjoutComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAjoutCompMouseClicked(evt);
            }
        });

        buttonRetourComp.setText("Retour");
        buttonRetourComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRetourCompMouseClicked(evt);
            }
        });

        labelAjoutComp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelAjoutComp.setText("Ajouter Compétences");

        LabelLibFrAjoutComp.setText("Libellé en français :");

        TextLibelleFrAjoutAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLibelleFrAjoutAccueilActionPerformed(evt);
            }
        });

        labelLibEnAjoutComp.setText("Libellé en anglais :");

        LabelIdAjoutComp.setText("Identifiant : ");

        javax.swing.GroupLayout PanelAjoutCompLayout = new javax.swing.GroupLayout(PanelAjoutComp);
        PanelAjoutComp.setLayout(PanelAjoutCompLayout);
        PanelAjoutCompLayout.setHorizontalGroup(
            PanelAjoutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjoutCompLayout.createSequentialGroup()
                .addGroup(PanelAjoutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAjoutCompLayout.createSequentialGroup()
                        .addGap(887, 887, 887)
                        .addComponent(LabelAjouterCompVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAjoutCompLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(labelAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAjoutCompLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAjoutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelMsgErreurAjoutComp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAjoutCompLayout.createSequentialGroup()
                                .addComponent(buttonRetourComp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(buttonAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelIdAjoutComp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextIdAjoutComp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelLibFrAjoutComp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLibEnAjoutComp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextLibelleFrAjoutAccueil, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextLibelleEnAjoutAccueil, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAjoutCompLayout.setVerticalGroup(
            PanelAjoutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjoutCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAjoutComp)
                .addGap(26, 26, 26)
                .addComponent(LabelIdAjoutComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIdAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLibFrAjoutComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextLibelleFrAjoutAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLibEnAjoutComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextLibelleEnAjoutAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelMsgErreurAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(PanelAjoutCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRetourComp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138)
                .addComponent(LabelAjouterCompVerif, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRetourCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetourCompMouseClicked
        this.dispose();
    }//GEN-LAST:event_buttonRetourCompMouseClicked

    private void buttonAjoutCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAjoutCompMouseClicked
       
        if(this.Verifier()){
            if(this.entreprise.ajoutCompétence(this.TextIdAjoutComp.getText(), this.TextLibelleEnAjoutAccueil.getText(), this.TextLibelleFrAjoutAccueil.getText())){
                this.dispose();
            } else {
                this.LabelMsgErreurAjoutComp.setText("Cette identifiant existe déjà");
            }
        } else {
            this.LabelMsgErreurAjoutComp.setText("Saisie non complette du formulaire");
        }
    }//GEN-LAST:event_buttonAjoutCompMouseClicked

    private void TextLibelleFrAjoutAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLibelleFrAjoutAccueilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLibelleFrAjoutAccueilActionPerformed

    public boolean Verifier() 
        {
            boolean verifier = true;
            if((this.TextIdAjoutComp.getText().equals("")) || (this.TextLibelleEnAjoutAccueil.getText().equals("")) || (this.TextLibelleFrAjoutAccueil.getText().equals(""))){
                verifier = false;        
            }
            return verifier;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAjouteComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAjouteComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAjouteComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceGraphiqueAjouteComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new interfaceGraphiqueAjouteComp().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(interfaceGraphiqueAjouteComp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAjouterCompVerif;
    private javax.swing.JLabel LabelIdAjoutComp;
    private javax.swing.JLabel LabelLibFrAjoutComp;
    private javax.swing.JLabel LabelMsgErreurAjoutComp;
    private javax.swing.JPanel PanelAjoutComp;
    private javax.swing.JTextField TextIdAjoutComp;
    private javax.swing.JTextField TextLibelleEnAjoutAccueil;
    private javax.swing.JTextField TextLibelleFrAjoutAccueil;
    private javax.swing.JButton buttonAjoutComp;
    private javax.swing.JButton buttonRetourComp;
    private javax.swing.JLabel labelAjoutComp;
    private javax.swing.JLabel labelLibEnAjoutComp;
    // End of variables declaration//GEN-END:variables
}
