/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Competence.Competence;
import Entreprise.Entreprise;
import Mission.Mission;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jmachado
 */
public class InterfaceGraphiqueFicheDetailsMissions extends javax.swing.JFrame {
    Entreprise e;
    /**
     * Creates new form InterfaceGraphiqueFicheDetailsMissions
     */
    public InterfaceGraphiqueFicheDetailsMissions() {
        initComponents();
        e = new Entreprise();
        Mission m = this.e.getIdModifMission();
        this.LabelTypeDetailsMissions.setText("Type : "+m.getType());
        this.LabelDateDebDetailsMission.setText("Date de début :"+m.getDateDebutFr());
        this.LabelDateFinDetailsMissions.setText("Date de fin :"+m.getDateFinFr());
        this.jLabel1.setText("Nombre de personne affecté au total :"+m.getTotalPersonne());
        this.identifiant.setText("Identifiant: "+m.getId());
        initTableCompet();
        initTablePerso();
    }
    
    private void initTableCompet(){
        TreeMap<String, Integer> tabCompet = this.e.getIdModifMission().getComptNbPersonne();
        DefaultTableModel model = (DefaultTableModel) this.tableCompetence2.getModel();
        Set<String> keys = tabCompet.keySet();
        for(String key: keys){
            Competence c = this.e.getTCompetences().get(key);
            model.addRow(new Object[]{c.toString()+" --"+tabCompet.get(key)});
        }
    }
    
    private void initTablePerso(){
        TreeMap<Integer,String> tabPerso = new TreeMap<Integer,String>();
        tabPerso = this.e.getIdModifMission().getTabPerso();
        DefaultTableModel model = (DefaultTableModel) this.tablePerso.getModel();
        Set<Integer> keys = tabPerso.keySet();
        for(Integer key: keys){
            model.addRow(new Object[]{tabPerso.get(key).toString(),e.getTPersonnels().get(key).toStringCsv()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFicheDetailsMissions = new javax.swing.JPanel();
        LabelDetailsMissions = new javax.swing.JLabel();
        LabelTypeDetailsMissions = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelDateDebDetailsMission = new javax.swing.JLabel();
        LabelDateFinDetailsMissions = new javax.swing.JLabel();
        ButtonRetourDetailsMissions = new javax.swing.JButton();
        ScrollpaneAjoutPers2 = new javax.swing.JScrollPane();
        tableCompetence2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePerso = new javax.swing.JTable();
        identifiant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFicheDetailsMissions.setBackground(new java.awt.Color(225, 225, 213));

        LabelDetailsMissions.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        LabelDetailsMissions.setText("Détails Missions");

        LabelTypeDetailsMissions.setText("Type:");

        jLabel1.setText("Nombre de personnes :");

        LabelDateDebDetailsMission.setText("Date début :");

        LabelDateFinDetailsMissions.setText("Date fin :");

        ButtonRetourDetailsMissions.setText("Retour");
        ButtonRetourDetailsMissions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonRetourDetailsMissionsMouseClicked(evt);
            }
        });

        tableCompetence2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant -- Libellé de la compétence -- Besoin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCompetence2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScrollpaneAjoutPers2.setViewportView(tableCompetence2);

        tablePerso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compétence", "Personnel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerso.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablePerso);

        identifiant.setText("Identifiant:");

        javax.swing.GroupLayout PanelFicheDetailsMissionsLayout = new javax.swing.GroupLayout(PanelFicheDetailsMissions);
        PanelFicheDetailsMissions.setLayout(PanelFicheDetailsMissionsLayout);
        PanelFicheDetailsMissionsLayout.setHorizontalGroup(
            PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(LabelDetailsMissions)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(ScrollpaneAjoutPers2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTypeDetailsMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identifiant)
                            .addComponent(jLabel1)
                            .addComponent(LabelDateFinDetailsMissions)
                            .addComponent(LabelDateDebDetailsMission))
                        .addGap(0, 709, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonRetourDetailsMissions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFicheDetailsMissionsLayout.setVerticalGroup(
            PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(identifiant)
                .addGap(39, 39, 39)
                .addComponent(LabelTypeDetailsMissions)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(LabelDateDebDetailsMission)
                .addGap(43, 43, 43)
                .addComponent(LabelDateFinDetailsMissions)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDetailsMissions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollpaneAjoutPers2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(ButtonRetourDetailsMissions)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFicheDetailsMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFicheDetailsMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRetourDetailsMissionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRetourDetailsMissionsMouseClicked
        InterfaceGraphiqueMissions Missions = new InterfaceGraphiqueMissions();
        this.dispose();
        Missions.setVisible(true);
    }//GEN-LAST:event_ButtonRetourDetailsMissionsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphiqueFicheDetailsMissions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRetourDetailsMissions;
    private javax.swing.JLabel LabelDateDebDetailsMission;
    private javax.swing.JLabel LabelDateFinDetailsMissions;
    private javax.swing.JLabel LabelDetailsMissions;
    private javax.swing.JLabel LabelTypeDetailsMissions;
    private javax.swing.JPanel PanelFicheDetailsMissions;
    private javax.swing.JScrollPane ScrollpaneAjoutPers2;
    private javax.swing.JLabel identifiant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCompetence2;
    private javax.swing.JTable tablePerso;
    // End of variables declaration//GEN-END:variables
}
