/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Competence.Competence;
import Entreprise.Entreprise;
import java.io.IOException;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author clementraphaell
 */
public class InterfaceGraphiqueModifierComp extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphiqueModifierComp
     */
    public InterfaceGraphiqueModifierComp() throws IOException {
        initComponents();
        Entreprise e = new Entreprise();
        this.initTabCompetences();
        this.remplissage();
        
    }
    
    private void remplissage() throws IOException{
        Entreprise e = new Entreprise();
        Set<String> keys = Entreprise.tCompetences.keySet();
        for(String key: keys){
            Competence p = Entreprise.tCompetences.get(key);
            this.comboBoxCompModifComp.addItem(p.toString());
        }
    }

    private void initTabCompetences() {
        DefaultTableModel model = (DefaultTableModel) tableModifierComp.getModel();
        Iterator i = Entreprise.tCompetences.keySet().iterator();
        String clef = null;
        Competence valeur = null;
        while (i.hasNext())
        {
            clef = (String)i.next();
            valeur = Entreprise.tCompetences.get(clef);
            model.addRow(new Object[]{valeur.getId(), valeur.getLibelleFr()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCodeModifComp = new javax.swing.JLabel();
        textFieldCodeModifComp = new javax.swing.JTextField();
        labelDescrModifComp = new javax.swing.JLabel();
        textFieldDescrModifComp = new javax.swing.JTextField();
        buttonModifModifComp = new javax.swing.JButton();
        buttonRetourModifComp = new javax.swing.JButton();
        labelModifComp = new javax.swing.JLabel();
        labelCompModifComp = new javax.swing.JLabel();
        comboBoxCompModifComp = new javax.swing.JComboBox<>();
        labelNomModifComp = new javax.swing.JLabel();
        textFieldNomModifComp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaModifCompVerif = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ButtonModifCompSupprimer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableModifierComp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 225, 213));

        labelCodeModifComp.setText("Code :");

        labelDescrModifComp.setText("Description :");

        textFieldDescrModifComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDescrModifCompActionPerformed(evt);
            }
        });

        buttonModifModifComp.setText("Modifier");
        buttonModifModifComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonModifModifCompMouseClicked(evt);
            }
        });

        buttonRetourModifComp.setText("Retour");
        buttonRetourModifComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRetourModifCompMouseClicked(evt);
            }
        });

        labelModifComp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelModifComp.setText("Modifier Compétences");

        labelCompModifComp.setText("Compétences :");

        comboBoxCompModifComp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxCompModifCompItemStateChanged(evt);
            }
        });

        labelNomModifComp.setText("Nom :");

        TextAreaModifCompVerif.setColumns(20);
        TextAreaModifCompVerif.setRows(5);
        jScrollPane1.setViewportView(TextAreaModifCompVerif);

        jLabel1.setText("Verification:");

        ButtonModifCompSupprimer.setText("Supprimer");

        jLabel2.setText("Liste:");

        tableModifierComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Identifiant", "Description"
            }
        ));
        jScrollPane2.setViewportView(tableModifierComp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonRetourModifComp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(labelModifComp))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(buttonModifModifComp)
                                .addGap(63, 63, 63)
                                .addComponent(ButtonModifCompSupprimer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelCodeModifComp)
                                                .addComponent(labelNomModifComp))
                                            .addGap(35, 35, 35)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textFieldNomModifComp, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                                .addComponent(textFieldCodeModifComp)))
                                        .addComponent(jLabel1)
                                        .addComponent(labelDescrModifComp)
                                        .addComponent(jLabel2)
                                        .addComponent(textFieldDescrModifComp)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelCompModifComp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxCompModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModifComp)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompModifComp)
                    .addComponent(comboBoxCompModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomModifComp)
                    .addComponent(textFieldNomModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCodeModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodeModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescrModifComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDescrModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModifModifComp)
                    .addComponent(ButtonModifCompSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRetourModifComp)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRetourModifCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetourModifCompMouseClicked
        // TODO add your handling code here:
        InterfaceGraphiqueCompetences  Competences = null;
        try {
            Competences = new InterfaceGraphiqueCompetences();
        } catch (IOException ex) {
            Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        Competences.setVisible(true);
    }//GEN-LAST:event_buttonRetourModifCompMouseClicked

    private void textFieldDescrModifCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDescrModifCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDescrModifCompActionPerformed

    private void comboBoxCompModifCompItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxCompModifCompItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCompModifCompItemStateChanged

    private void buttonModifModifCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModifModifCompMouseClicked
        // TODO add your handling code here:
        boolean remplie = this.Verifier();
        String lignes = new String();
        if(remplie == true){
            //tableAjouterPers.add(lignes);
            TextAreaModifCompVerif.setText("Bien remplie");
        }
        else
            TextAreaModifCompVerif.setText("Vous n'avez pas tous remplie");
    }//GEN-LAST:event_buttonModifModifCompMouseClicked

    public boolean Verifier() 
        {
            boolean verifier = true;
            if((textFieldCodeModifComp.getText().equals(""))||(textFieldDescrModifComp.getText().equals(""))||(textFieldNomModifComp.getText().equals(""))){
                verifier = false;        
            }
            return verifier;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfaceGraphiqueModifierComp().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonModifCompSupprimer;
    private javax.swing.JTextArea TextAreaModifCompVerif;
    private javax.swing.JButton buttonModifModifComp;
    private javax.swing.JButton buttonRetourModifComp;
    private javax.swing.JComboBox<String> comboBoxCompModifComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCodeModifComp;
    private javax.swing.JLabel labelCompModifComp;
    private javax.swing.JLabel labelDescrModifComp;
    private javax.swing.JLabel labelModifComp;
    private javax.swing.JLabel labelNomModifComp;
    private javax.swing.JTable tableModifierComp;
    private javax.swing.JTextField textFieldCodeModifComp;
    private javax.swing.JTextField textFieldDescrModifComp;
    private javax.swing.JTextField textFieldNomModifComp;
    // End of variables declaration//GEN-END:variables
}
