/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author clementraphaell
 */
public class InterfaceGraphiqueCreationMissions extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphiqueCreationMissions
     */
    public InterfaceGraphiqueCreationMissions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCreationMissions = new javax.swing.JPanel();
        LabelCreationMission = new javax.swing.JLabel();
        ComboBoxTypeCreationMissions = new javax.swing.JComboBox<>();
        LabelTypeCreationMission = new javax.swing.JLabel();
        LabelNbPersCreationMission = new javax.swing.JLabel();
        TextFieldNbPersonneCreationMissions = new javax.swing.JTextField();
        PanelCompCreationMissions = new javax.swing.JPanel();
        ComboBoxCompCreationMission = new javax.swing.JComboBox<>();
        LabelNbPersonCompRequise = new javax.swing.JLabel();
        TextFieldPersCompCreationMission = new javax.swing.JTextField();
        ButtonAjouterCreationMission = new javax.swing.JButton();
        PanelDate = new javax.swing.JPanel();
        LabelDateDebut = new javax.swing.JLabel();
        TextFieldDateDebut = new javax.swing.JTextField();
        LabelDateFin = new javax.swing.JLabel();
        TextFieldDateFin = new javax.swing.JTextField();
        ButtonRetourCreationMissions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelCreationMission.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        LabelCreationMission.setText("Creation Missions");

        LabelTypeCreationMission.setText("Type :");

        LabelNbPersCreationMission.setText("Nombre de personne :");

        PanelCompCreationMissions.setBorder(javax.swing.BorderFactory.createTitledBorder("Competences"));

        LabelNbPersonCompRequise.setText("Personne ayant cette competence :");

        ButtonAjouterCreationMission.setText("Ajouter");

        javax.swing.GroupLayout PanelCompCreationMissionsLayout = new javax.swing.GroupLayout(PanelCompCreationMissions);
        PanelCompCreationMissions.setLayout(PanelCompCreationMissionsLayout);
        PanelCompCreationMissionsLayout.setHorizontalGroup(
            PanelCompCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompCreationMissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNbPersonCompRequise)
                .addGap(18, 18, 18)
                .addComponent(TextFieldPersCompCreationMission, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(ButtonAjouterCreationMission)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompCreationMissionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboBoxCompCreationMission, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        PanelCompCreationMissionsLayout.setVerticalGroup(
            PanelCompCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompCreationMissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxCompCreationMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCompCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNbPersonCompRequise, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldPersCompCreationMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompCreationMissionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAjouterCreationMission)
                .addContainerGap())
        );

        PanelDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));

        LabelDateDebut.setText("Debut :");

        LabelDateFin.setText("Fin :");

        javax.swing.GroupLayout PanelDateLayout = new javax.swing.GroupLayout(PanelDate);
        PanelDate.setLayout(PanelDateLayout);
        PanelDateLayout.setHorizontalGroup(
            PanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDateLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelDateDebut)
                .addGap(18, 18, 18)
                .addComponent(TextFieldDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(LabelDateFin)
                .addGap(32, 32, 32)
                .addComponent(TextFieldDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDateLayout.setVerticalGroup(
            PanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDateLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDateDebut)
                    .addComponent(TextFieldDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDateFin)
                    .addComponent(TextFieldDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ButtonRetourCreationMissions.setText("Retour");
        ButtonRetourCreationMissions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonRetourCreationMissionsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelCreationMissionsLayout = new javax.swing.GroupLayout(PanelCreationMissions);
        PanelCreationMissions.setLayout(PanelCreationMissionsLayout);
        PanelCreationMissionsLayout.setHorizontalGroup(
            PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCreationMissionsLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addGroup(PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelCompCreationMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCreationMissionsLayout.createSequentialGroup()
                        .addGroup(PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelNbPersCreationMission)
                            .addComponent(LabelTypeCreationMission))
                        .addGroup(PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCreationMissionsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelCreationMission))
                            .addGroup(PanelCreationMissionsLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(TextFieldNbPersonneCreationMissions, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCreationMissionsLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(ComboBoxTypeCreationMissions, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(PanelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCreationMissionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonRetourCreationMissions)
                .addContainerGap())
        );
        PanelCreationMissionsLayout.setVerticalGroup(
            PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCreationMissionsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelCreationMission)
                .addGap(109, 109, 109)
                .addGroup(PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTypeCreationMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTypeCreationMission))
                .addGap(18, 18, 18)
                .addGroup(PanelCreationMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNbPersCreationMission)
                    .addComponent(TextFieldNbPersonneCreationMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(PanelCompCreationMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ButtonRetourCreationMissions))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCreationMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCreationMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRetourCreationMissionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRetourCreationMissionsMouseClicked
        InterfaceGraphiqueMissions Missions = null;
        try {
            Missions = new InterfaceGraphiqueMissions();
        } catch (NumberFormatException ex) {
            Logger.getLogger(InterfaceGraphiqueMissions.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        Missions.setVisible(true);
        
    }//GEN-LAST:event_ButtonRetourCreationMissionsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCreationMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCreationMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCreationMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCreationMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphiqueCreationMissions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAjouterCreationMission;
    private javax.swing.JButton ButtonRetourCreationMissions;
    private javax.swing.JComboBox<String> ComboBoxCompCreationMission;
    private javax.swing.JComboBox<String> ComboBoxTypeCreationMissions;
    private javax.swing.JLabel LabelCreationMission;
    private javax.swing.JLabel LabelDateDebut;
    private javax.swing.JLabel LabelDateFin;
    private javax.swing.JLabel LabelNbPersCreationMission;
    private javax.swing.JLabel LabelNbPersonCompRequise;
    private javax.swing.JLabel LabelTypeCreationMission;
    private javax.swing.JPanel PanelCompCreationMissions;
    private javax.swing.JPanel PanelCreationMissions;
    private javax.swing.JPanel PanelDate;
    private javax.swing.JTextField TextFieldDateDebut;
    private javax.swing.JTextField TextFieldDateFin;
    private javax.swing.JTextField TextFieldNbPersonneCreationMissions;
    private javax.swing.JTextField TextFieldPersCompCreationMission;
    // End of variables declaration//GEN-END:variables
}
