/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author clementraphaell
 */
public class InterfaceGraphiqueFicheDetailsMissions extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphiqueFicheDetailsMissions
     */
    public InterfaceGraphiqueFicheDetailsMissions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFicheDetailsMissions = new javax.swing.JPanel();
        LabelDetailsMissions = new javax.swing.JLabel();
        LabelTypeDetailsMissions = new javax.swing.JLabel();
        TextFieldTypeDetailsMissions = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextFieldNbPersonneDetailsMissions = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCompetenceDetailsMissions = new javax.swing.JTable();
        LabelDateDebDetailsMission = new javax.swing.JLabel();
        TextFieldDateDebDetailsMissions = new javax.swing.JTextField();
        LabelDateFinDetailsMissions = new javax.swing.JLabel();
        TextFieldDateFinDetailsMissions = new javax.swing.JTextField();
        ButtonRetourDetailsMissions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelDetailsMissions.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        LabelDetailsMissions.setText("Détails Missions");

        LabelTypeDetailsMissions.setText("Type:");

        jLabel1.setText("Nombre de personnes :");

        TableCompetenceDetailsMissions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Compétences", "Nombre de personnes possédant la compétence"
            }
        ));
        jScrollPane1.setViewportView(TableCompetenceDetailsMissions);

        LabelDateDebDetailsMission.setText("Date début :");

        LabelDateFinDetailsMissions.setText("Date fin :");

        TextFieldDateFinDetailsMissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDateFinDetailsMissionsActionPerformed(evt);
            }
        });

        ButtonRetourDetailsMissions.setText("Retour");

        javax.swing.GroupLayout PanelFicheDetailsMissionsLayout = new javax.swing.GroupLayout(PanelFicheDetailsMissions);
        PanelFicheDetailsMissions.setLayout(PanelFicheDetailsMissionsLayout);
        PanelFicheDetailsMissionsLayout.setHorizontalGroup(
            PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addComponent(LabelDetailsMissions)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                                .addComponent(LabelTypeDetailsMissions)
                                .addGap(79, 79, 79)
                                .addComponent(TextFieldTypeDetailsMissions, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                                .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFicheDetailsMissionsLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18))
                                    .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelDateFinDetailsMissions)
                                            .addComponent(LabelDateDebDetailsMission))
                                        .addGap(54, 54, 54)))
                                .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextFieldNbPersonneDetailsMissions)
                                    .addComponent(TextFieldDateDebDetailsMissions, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(TextFieldDateFinDetailsMissions))))
                        .addGap(71, 71, 71))
                    .addComponent(ButtonRetourDetailsMissions, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        PanelFicheDetailsMissionsLayout.setVerticalGroup(
            PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(LabelDetailsMissions)
                .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTypeDetailsMissions)
                            .addComponent(TextFieldTypeDetailsMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextFieldNbPersonneDetailsMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDateDebDetailsMission)
                            .addComponent(TextFieldDateDebDetailsMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(PanelFicheDetailsMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDateFinDetailsMissions)
                            .addComponent(TextFieldDateFinDetailsMissions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelFicheDetailsMissionsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(ButtonRetourDetailsMissions))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFicheDetailsMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFicheDetailsMissions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldDateFinDetailsMissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDateFinDetailsMissionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDateFinDetailsMissionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueFicheDetailsMissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphiqueFicheDetailsMissions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRetourDetailsMissions;
    private javax.swing.JLabel LabelDateDebDetailsMission;
    private javax.swing.JLabel LabelDateFinDetailsMissions;
    private javax.swing.JLabel LabelDetailsMissions;
    private javax.swing.JLabel LabelTypeDetailsMissions;
    private javax.swing.JPanel PanelFicheDetailsMissions;
    private javax.swing.JTable TableCompetenceDetailsMissions;
    private javax.swing.JTextField TextFieldDateDebDetailsMissions;
    private javax.swing.JTextField TextFieldDateFinDetailsMissions;
    private javax.swing.JTextField TextFieldNbPersonneDetailsMissions;
    private javax.swing.JTextField TextFieldTypeDetailsMissions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
